@url = http://localhost:3000
# @url = https://api.cha-ching.it

### Get issues in repos the app has access to
GET {{ url }}/github/issues?installationId=YOUR_INSTALLATION_ID
Accept: application/json

### Create a bounty
POST {{ url }}/github/bounties
Content-Type: application/json
Accept: application/json

{
  "repo": "https://github.com/cha-ching-team/go-ethereum",
  "issue": 2,
  "amount": 989,
  "coin": "USDC",
  "chain_id": "1",
  "bountyOwner": "gsmachado"
}

### Get bounties by bountyOwner
GET {{ url }}/github/bounties?bountyOwner=gsmachado
Accept: application/json 

### Get all bounties
GET {{ url }}/github/bounties
Accept: application/json 

### Recommend bounties based on user skills
POST {{ url }}/github/recommend-bounties
Content-Type: application/json
Accept: application/json

{
  "prompt": "I'm good at coding in Java, and I'm learning Kotlin. Looking for bounties that match my skills."
}
